# this is the name of workflow that will be displayed in the Actions Tab
name: NEW-CICD

# Manual click (deliver) workflow whenever user need
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container Build" 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
      
